---

- hosts: all
  become: true
  pre_tasks:

    - name: install updates (CentOS)
      tags: always
      package:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: install updates (Ubuntu)
      tags: always
      package:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

    - name: install apache/php and update repo index for ubuntu servers
      tags: apache,apache2,ubuntu
      package:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache/php and update repo index for centos
      tags: apache,centos,httpd
      package:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"

    - name: copy default html file for site
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package (Ubuntu)
      tags: ubuntu,mariadb,db
      package:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest

